### PR TITLE
RHCLOUD-34971 : Return 404 when querying a non-existent service account

### PR DESCRIPTION
**Pull request by adamrdrew**
This creates a special condition that failed requests to get a service account, such as with an invalid ID, return a 404, matching prod. Other failures are left as 500s because it wasn’t requested to change those.

### CODE REVIEW

**Comment by adamrdrew** [comment]
Meh I tried to fix the gitlab action tests but there are multiple problems and I’m not sure what else to do. The lint and PR build are green.

**Comment by adamrdrew** [comment]
OK I give up on trying to fix the github actions. They were broken when I got here. If I could have fixed them with a couple of tweaks cool, but that didn’t pan out. Reverted them.

**Comment by Victoremepunto** [comment]
@adamrdrew I can give it a try, gimme a sec

**Comment by adamrdrew** [comment]
I added some documentation so people can run tests locally and in a debug session in VSCode. I also found through my test that there was a bug in the code that had gone unnoticed: if you passed totally bogus and invalid intput to the endpoint it returned a 200 with an empty array which is unexpected

**Pull request merged**
